apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cigg-app-ingress
  namespace: cigg-app
spec:
  rules:
  - host: cigg-app.local
    http:
      paths:
      # BACKEND: match /api first
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: cigg-app-backend-service
            port:
              number: 3000
      # FRONTEND: catch-all
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-service
            port:
              number: 80
