apiVersion: v1
kind: ConfigMap
metadata:
  name: cigg-app-db-migration-sql
  namespace: cigg-app
data:
  V1__init.sql: |
    CREATE TABLE IF NOT EXISTS entries (
        id SERIAL PRIMARY KEY,
        quantity INTEGER NOT NULL CHECK (quantity > 0),
        location VARCHAR(255) NOT NULL,
        notes TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
